# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - configure-cicd # TODO: remove this branch from allow-list when done testing/debugging CI/CD configuration
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Open Watcom C v2 installer for DOS
        run: wget -nv -O OWC2INST.EXE https://github.com/open-watcom/open-watcom-v2/releases/download/2022-07-01-Build/open-watcom-2_0-c-dos.exe

      - name: Use cicd-qemu-dos-docker Docker container
        uses: docker://ghcr.io/volkertb/cicd-qemu-dos-docker:v1.2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
